import { Template } from '../types/builder';

export const TEMPLATES: Template[] = [
  {
    id: 'classic-elegance',
    name: 'Classic Elegance',
    description: 'Timeless and sophisticated wedding site',
    tags: ['classic', 'elegant'],
    sections: [
      { sectionType: 'hero', variantKey: 'elegant', order: 0 },
      { sectionType: 'story', variantKey: 'elegant', order: 1 },
      { sectionType: 'timeline', variantKey: 'classic', order: 2 },
      { sectionType: 'gallery', variantKey: 'elegant', order: 3 },
      { sectionType: 'schedule', variantKey: 'classic', order: 4 },
      { sectionType: 'location', variantKey: 'classic', order: 5 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 6 },
      { sectionType: 'footer', variantKey: 'elegant', order: 7 },
    ],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    description: 'Clean and contemporary design',
    tags: ['modern', 'minimal'],
    sections: [
      { sectionType: 'hero', variantKey: 'minimal', order: 0 },
      { sectionType: 'story', variantKey: 'minimal', order: 1 },
      { sectionType: 'gallery', variantKey: 'masonry', order: 2 },
      { sectionType: 'location', variantKey: 'minimal', order: 3 },
      { sectionType: 'rsvp', variantKey: 'minimal', order: 4 },
      { sectionType: 'footer', variantKey: 'minimal', order: 5 },
    ],
    createdAt: '2026-01-02',
    updatedAt: '2026-01-02',
  },
  {
    id: 'bold-modern',
    name: 'Bold Modern',
    description: 'Statement-making contemporary design',
    tags: ['modern', 'bold'],
    sections: [
      { sectionType: 'hero', variantKey: 'modern', order: 0 },
      { sectionType: 'story', variantKey: 'modern', order: 1 },
      { sectionType: 'timeline', variantKey: 'modern', order: 2 },
      { sectionType: 'gallery', variantKey: 'classic', order: 3 },
      { sectionType: 'schedule', variantKey: 'modern', order: 4 },
      { sectionType: 'location', variantKey: 'modern', order: 5 },
      { sectionType: 'rsvp', variantKey: 'modern', order: 6 },
      { sectionType: 'footer', variantKey: 'classic', order: 7 },
    ],
    createdAt: '2026-01-03',
    updatedAt: '2026-01-03',
  },
  {
    id: 'romantic-dream',
    name: 'Romantic Dream',
    description: 'Soft and dreamy romantic aesthetic',
    tags: ['romantic', 'whimsical'],
    sections: [
      { sectionType: 'hero', variantKey: 'romantic', order: 0 },
      { sectionType: 'story', variantKey: 'classic', order: 1 },
      { sectionType: 'timeline', variantKey: 'classic', order: 2 },
      { sectionType: 'gallery', variantKey: 'carousel', order: 3 },
      { sectionType: 'location', variantKey: 'classic', order: 4 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 5 },
      { sectionType: 'footer', variantKey: 'elegant', order: 6 },
    ],
    createdAt: '2026-01-04',
    updatedAt: '2026-01-04',
  },
  {
    id: 'classic-traditional',
    name: 'Classic Traditional',
    description: 'Traditional wedding site with timeless appeal',
    tags: ['classic'],
    sections: [
      { sectionType: 'hero', variantKey: 'classic', order: 0 },
      { sectionType: 'story', variantKey: 'classic', order: 1 },
      { sectionType: 'timeline', variantKey: 'classic', order: 2 },
      { sectionType: 'gallery', variantKey: 'classic', order: 3 },
      { sectionType: 'schedule', variantKey: 'classic', order: 4 },
      { sectionType: 'location', variantKey: 'classic', order: 5 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 6 },
      { sectionType: 'footer', variantKey: 'classic', order: 7 },
    ],
    createdAt: '2026-01-05',
    updatedAt: '2026-01-05',
  },
  {
    id: 'luxe-wedding',
    name: 'Luxe Wedding',
    description: 'Luxury and high-end wedding experience',
    tags: ['luxe', 'elegant'],
    sections: [
      { sectionType: 'hero', variantKey: 'elegant', order: 0 },
      { sectionType: 'story', variantKey: 'elegant', order: 1 },
      { sectionType: 'gallery', variantKey: 'elegant', order: 2 },
      { sectionType: 'schedule', variantKey: 'classic', order: 3 },
      { sectionType: 'location', variantKey: 'classic', order: 4 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 5 },
      { sectionType: 'footer', variantKey: 'elegant', order: 6 },
    ],
    createdAt: '2026-01-06',
    updatedAt: '2026-01-06',
  },
  {
    id: 'simple-story',
    name: 'Simple Story',
    description: 'Focus on your love story with minimal distractions',
    tags: ['minimal'],
    sections: [
      { sectionType: 'hero', variantKey: 'minimal', order: 0 },
      { sectionType: 'story', variantKey: 'minimal', order: 1 },
      { sectionType: 'location', variantKey: 'minimal', order: 2 },
      { sectionType: 'rsvp', variantKey: 'minimal', order: 3 },
      { sectionType: 'footer', variantKey: 'minimal', order: 4 },
    ],
    createdAt: '2026-01-07',
    updatedAt: '2026-01-07',
  },
  {
    id: 'full-featured',
    name: 'Full Featured',
    description: 'Complete wedding site with all sections',
    tags: ['classic'],
    sections: [
      { sectionType: 'hero', variantKey: 'classic', order: 0 },
      { sectionType: 'story', variantKey: 'classic', order: 1 },
      { sectionType: 'timeline', variantKey: 'vertical', order: 2 },
      { sectionType: 'gallery', variantKey: 'masonry', order: 3 },
      { sectionType: 'schedule', variantKey: 'cards', order: 4 },
      { sectionType: 'location', variantKey: 'classic', order: 5 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 6 },
      { sectionType: 'footer', variantKey: 'classic', order: 7 },
    ],
    createdAt: '2026-01-08',
    updatedAt: '2026-01-08',
  },
  {
    id: 'modern-gallery',
    name: 'Modern Gallery',
    description: 'Photo-focused modern wedding site',
    tags: ['modern'],
    sections: [
      { sectionType: 'hero', variantKey: 'modern', order: 0 },
      { sectionType: 'gallery', variantKey: 'masonry', order: 1 },
      { sectionType: 'story', variantKey: 'modern', order: 2 },
      { sectionType: 'location', variantKey: 'modern', order: 3 },
      { sectionType: 'rsvp', variantKey: 'modern', order: 4 },
      { sectionType: 'footer', variantKey: 'classic', order: 5 },
    ],
    createdAt: '2026-01-09',
    updatedAt: '2026-01-09',
  },
  {
    id: 'timeline-focused',
    name: 'Timeline Focused',
    description: 'Highlight your journey together',
    tags: ['classic'],
    sections: [
      { sectionType: 'hero', variantKey: 'classic', order: 0 },
      { sectionType: 'timeline', variantKey: 'classic', order: 1 },
      { sectionType: 'story', variantKey: 'classic', order: 2 },
      { sectionType: 'gallery', variantKey: 'classic', order: 3 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 4 },
      { sectionType: 'footer', variantKey: 'classic', order: 5 },
    ],
    createdAt: '2026-01-10',
    updatedAt: '2026-01-10',
  },
  {
    id: 'elegant-minimal',
    name: 'Elegant Minimal',
    description: 'Sophisticated simplicity',
    tags: ['elegant', 'minimal'],
    sections: [
      { sectionType: 'hero', variantKey: 'minimal', order: 0 },
      { sectionType: 'story', variantKey: 'elegant', order: 1 },
      { sectionType: 'gallery', variantKey: 'elegant', order: 2 },
      { sectionType: 'location', variantKey: 'minimal', order: 3 },
      { sectionType: 'rsvp', variantKey: 'minimal', order: 4 },
      { sectionType: 'footer', variantKey: 'elegant', order: 5 },
    ],
    createdAt: '2026-01-11',
    updatedAt: '2026-01-11',
  },
  {
    id: 'modern-romance',
    name: 'Modern Romance',
    description: 'Contemporary take on romantic design',
    tags: ['modern', 'romantic'],
    sections: [
      { sectionType: 'hero', variantKey: 'romantic', order: 0 },
      { sectionType: 'story', variantKey: 'modern', order: 1 },
      { sectionType: 'gallery', variantKey: 'carousel', order: 2 },
      { sectionType: 'schedule', variantKey: 'modern', order: 3 },
      { sectionType: 'location', variantKey: 'modern', order: 4 },
      { sectionType: 'rsvp', variantKey: 'modern', order: 5 },
      { sectionType: 'footer', variantKey: 'classic', order: 6 },
    ],
    createdAt: '2026-01-12',
    updatedAt: '2026-01-12',
  },
  {
    id: 'quick-start',
    name: 'Quick Start',
    description: 'Essential sections for a fast setup',
    tags: ['minimal'],
    sections: [
      { sectionType: 'hero', variantKey: 'minimal', order: 0 },
      { sectionType: 'location', variantKey: 'minimal', order: 1 },
      { sectionType: 'rsvp', variantKey: 'minimal', order: 2 },
      { sectionType: 'footer', variantKey: 'minimal', order: 3 },
    ],
    createdAt: '2026-01-13',
    updatedAt: '2026-01-13',
  },
  {
    id: 'gallery-showcase',
    name: 'Gallery Showcase',
    description: 'Let your photos tell the story',
    tags: ['modern'],
    sections: [
      { sectionType: 'hero', variantKey: 'modern', order: 0 },
      { sectionType: 'gallery', variantKey: 'masonry', order: 1 },
      { sectionType: 'gallery', variantKey: 'elegant', order: 2 },
      { sectionType: 'rsvp', variantKey: 'modern', order: 3 },
      { sectionType: 'footer', variantKey: 'classic', order: 4 },
    ],
    createdAt: '2026-01-14',
    updatedAt: '2026-01-14',
  },
  {
    id: 'detailed-schedule',
    name: 'Detailed Schedule',
    description: 'Perfect for multi-event weddings',
    tags: ['classic'],
    sections: [
      { sectionType: 'hero', variantKey: 'classic', order: 0 },
      { sectionType: 'schedule', variantKey: 'cards', order: 1 },
      { sectionType: 'schedule', variantKey: 'classic', order: 2 },
      { sectionType: 'location', variantKey: 'classic', order: 3 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 4 },
      { sectionType: 'footer', variantKey: 'classic', order: 5 },
    ],
    createdAt: '2026-01-15',
    updatedAt: '2026-01-15',
  },
  {
    id: 'story-first',
    name: 'Story First',
    description: 'Begin with your love story',
    tags: ['romantic'],
    sections: [
      { sectionType: 'hero', variantKey: 'romantic', order: 0 },
      { sectionType: 'story', variantKey: 'elegant', order: 1 },
      { sectionType: 'timeline', variantKey: 'classic', order: 2 },
      { sectionType: 'gallery', variantKey: 'carousel', order: 3 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 4 },
      { sectionType: 'footer', variantKey: 'elegant', order: 5 },
    ],
    createdAt: '2026-01-16',
    updatedAt: '2026-01-16',
  },
  {
    id: 'modern-classic',
    name: 'Modern Classic',
    description: 'Contemporary with classic touches',
    tags: ['modern', 'classic'],
    sections: [
      { sectionType: 'hero', variantKey: 'modern', order: 0 },
      { sectionType: 'story', variantKey: 'classic', order: 1 },
      { sectionType: 'gallery', variantKey: 'classic', order: 2 },
      { sectionType: 'schedule', variantKey: 'classic', order: 3 },
      { sectionType: 'location', variantKey: 'modern', order: 4 },
      { sectionType: 'rsvp', variantKey: 'modern', order: 5 },
      { sectionType: 'footer', variantKey: 'classic', order: 6 },
    ],
    createdAt: '2026-01-17',
    updatedAt: '2026-01-17',
  },
  {
    id: 'elegant-timeline',
    name: 'Elegant Timeline',
    description: 'Elegant journey presentation',
    tags: ['elegant'],
    sections: [
      { sectionType: 'hero', variantKey: 'elegant', order: 0 },
      { sectionType: 'timeline', variantKey: 'classic', order: 1 },
      { sectionType: 'gallery', variantKey: 'elegant', order: 2 },
      { sectionType: 'location', variantKey: 'classic', order: 3 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 4 },
      { sectionType: 'footer', variantKey: 'elegant', order: 5 },
    ],
    createdAt: '2026-01-18',
    updatedAt: '2026-01-18',
  },
  {
    id: 'minimal-chic',
    name: 'Minimal Chic',
    description: 'Less is more',
    tags: ['minimal'],
    sections: [
      { sectionType: 'hero', variantKey: 'minimal', order: 0 },
      { sectionType: 'story', variantKey: 'minimal', order: 1 },
      { sectionType: 'gallery', variantKey: 'masonry', order: 2 },
      { sectionType: 'rsvp', variantKey: 'minimal', order: 3 },
      { sectionType: 'footer', variantKey: 'minimal', order: 4 },
    ],
    createdAt: '2026-01-19',
    updatedAt: '2026-01-19',
  },
  {
    id: 'bold-statement',
    name: 'Bold Statement',
    description: 'Make an impact',
    tags: ['bold', 'modern'],
    sections: [
      { sectionType: 'hero', variantKey: 'modern', order: 0 },
      { sectionType: 'story', variantKey: 'modern', order: 1 },
      { sectionType: 'timeline', variantKey: 'modern', order: 2 },
      { sectionType: 'gallery', variantKey: 'masonry', order: 3 },
      { sectionType: 'schedule', variantKey: 'modern', order: 4 },
      { sectionType: 'location', variantKey: 'modern', order: 5 },
      { sectionType: 'rsvp', variantKey: 'modern', order: 6 },
      { sectionType: 'footer', variantKey: 'classic', order: 7 },
    ],
    createdAt: '2026-01-20',
    updatedAt: '2026-01-20',
  },
  {
    id: 'classic-luxe',
    name: 'Classic Luxe',
    description: 'Timeless luxury',
    tags: ['classic', 'luxe'],
    sections: [
      { sectionType: 'hero', variantKey: 'elegant', order: 0 },
      { sectionType: 'story', variantKey: 'elegant', order: 1 },
      { sectionType: 'timeline', variantKey: 'classic', order: 2 },
      { sectionType: 'gallery', variantKey: 'elegant', order: 3 },
      { sectionType: 'schedule', variantKey: 'classic', order: 4 },
      { sectionType: 'location', variantKey: 'classic', order: 5 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 6 },
      { sectionType: 'footer', variantKey: 'elegant', order: 7 },
    ],
    createdAt: '2026-01-21',
    updatedAt: '2026-01-21',
  },
  {
    id: 'whimsical-wonder',
    name: 'Whimsical Wonder',
    description: 'Playful and magical',
    tags: ['whimsical', 'romantic'],
    sections: [
      { sectionType: 'hero', variantKey: 'romantic', order: 0 },
      { sectionType: 'story', variantKey: 'classic', order: 1 },
      { sectionType: 'gallery', variantKey: 'carousel', order: 2 },
      { sectionType: 'timeline', variantKey: 'classic', order: 3 },
      { sectionType: 'location', variantKey: 'classic', order: 4 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 5 },
      { sectionType: 'footer', variantKey: 'elegant', order: 6 },
    ],
    createdAt: '2026-01-22',
    updatedAt: '2026-01-22',
  },
  {
    id: 'modern-elegance',
    name: 'Modern Elegance',
    description: 'Contemporary meets sophisticated',
    tags: ['modern', 'elegant'],
    sections: [
      { sectionType: 'hero', variantKey: 'modern', order: 0 },
      { sectionType: 'story', variantKey: 'elegant', order: 1 },
      { sectionType: 'gallery', variantKey: 'elegant', order: 2 },
      { sectionType: 'schedule', variantKey: 'modern', order: 3 },
      { sectionType: 'location', variantKey: 'modern', order: 4 },
      { sectionType: 'rsvp', variantKey: 'modern', order: 5 },
      { sectionType: 'footer', variantKey: 'elegant', order: 6 },
    ],
    createdAt: '2026-01-23',
    updatedAt: '2026-01-23',
  },
  {
    id: 'simple-elegant',
    name: 'Simple Elegant',
    description: 'Refined simplicity',
    tags: ['elegant', 'minimal'],
    sections: [
      { sectionType: 'hero', variantKey: 'elegant', order: 0 },
      { sectionType: 'story', variantKey: 'minimal', order: 1 },
      { sectionType: 'location', variantKey: 'minimal', order: 2 },
      { sectionType: 'rsvp', variantKey: 'minimal', order: 3 },
      { sectionType: 'footer', variantKey: 'elegant', order: 4 },
    ],
    createdAt: '2026-01-24',
    updatedAt: '2026-01-24',
  },
  {
    id: 'comprehensive',
    name: 'Comprehensive',
    description: 'Everything your guests need to know',
    tags: ['classic'],
    sections: [
      { sectionType: 'hero', variantKey: 'classic', order: 0 },
      { sectionType: 'story', variantKey: 'classic', order: 1 },
      { sectionType: 'timeline', variantKey: 'vertical', order: 2 },
      { sectionType: 'gallery', variantKey: 'classic', order: 3 },
      { sectionType: 'schedule', variantKey: 'cards', order: 4 },
      { sectionType: 'location', variantKey: 'classic', order: 5 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 6 },
      { sectionType: 'footer', variantKey: 'classic', order: 7 },
    ],
    createdAt: '2026-01-25',
    updatedAt: '2026-01-25',
  },
  {
    id: 'photo-story',
    name: 'Photo Story',
    description: 'Pictures and narrative combined',
    tags: ['modern'],
    sections: [
      { sectionType: 'hero', variantKey: 'modern', order: 0 },
      { sectionType: 'gallery', variantKey: 'masonry', order: 1 },
      { sectionType: 'story', variantKey: 'minimal', order: 2 },
      { sectionType: 'timeline', variantKey: 'vertical', order: 3 },
      { sectionType: 'rsvp', variantKey: 'modern', order: 4 },
      { sectionType: 'footer', variantKey: 'minimal', order: 5 },
    ],
    createdAt: '2026-01-26',
    updatedAt: '2026-01-26',
  },
  {
    id: 'classic-gallery',
    name: 'Classic Gallery',
    description: 'Traditional photo presentation',
    tags: ['classic'],
    sections: [
      { sectionType: 'hero', variantKey: 'classic', order: 0 },
      { sectionType: 'gallery', variantKey: 'classic', order: 1 },
      { sectionType: 'story', variantKey: 'classic', order: 2 },
      { sectionType: 'location', variantKey: 'classic', order: 3 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 4 },
      { sectionType: 'footer', variantKey: 'classic', order: 5 },
    ],
    createdAt: '2026-01-27',
    updatedAt: '2026-01-27',
  },
  {
    id: 'modern-timeline',
    name: 'Modern Timeline',
    description: 'Contemporary journey display',
    tags: ['modern'],
    sections: [
      { sectionType: 'hero', variantKey: 'modern', order: 0 },
      { sectionType: 'timeline', variantKey: 'modern', order: 1 },
      { sectionType: 'story', variantKey: 'modern', order: 2 },
      { sectionType: 'gallery', variantKey: 'masonry', order: 3 },
      { sectionType: 'rsvp', variantKey: 'modern', order: 4 },
      { sectionType: 'footer', variantKey: 'classic', order: 5 },
    ],
    createdAt: '2026-01-28',
    updatedAt: '2026-01-28',
  },
  {
    id: 'elegant-romance',
    name: 'Elegant Romance',
    description: 'Sophisticated romantic design',
    tags: ['elegant', 'romantic'],
    sections: [
      { sectionType: 'hero', variantKey: 'romantic', order: 0 },
      { sectionType: 'story', variantKey: 'elegant', order: 1 },
      { sectionType: 'timeline', variantKey: 'classic', order: 2 },
      { sectionType: 'gallery', variantKey: 'elegant', order: 3 },
      { sectionType: 'location', variantKey: 'classic', order: 4 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 5 },
      { sectionType: 'footer', variantKey: 'elegant', order: 6 },
    ],
    createdAt: '2026-01-29',
    updatedAt: '2026-01-29',
  },
  {
    id: 'minimal-modern',
    name: 'Minimal Modern',
    description: 'Pure contemporary design',
    tags: ['minimal', 'modern'],
    sections: [
      { sectionType: 'hero', variantKey: 'minimal', order: 0 },
      { sectionType: 'story', variantKey: 'minimal', order: 1 },
      { sectionType: 'timeline', variantKey: 'vertical', order: 2 },
      { sectionType: 'gallery', variantKey: 'masonry', order: 3 },
      { sectionType: 'location', variantKey: 'minimal', order: 4 },
      { sectionType: 'rsvp', variantKey: 'minimal', order: 5 },
      { sectionType: 'footer', variantKey: 'minimal', order: 6 },
    ],
    createdAt: '2026-01-30',
    updatedAt: '2026-01-30',
  },
  {
    id: 'classic-complete',
    name: 'Classic Complete',
    description: 'Full traditional wedding site',
    tags: ['classic'],
    sections: [
      { sectionType: 'hero', variantKey: 'classic', order: 0 },
      { sectionType: 'story', variantKey: 'classic', order: 1 },
      { sectionType: 'timeline', variantKey: 'classic', order: 2 },
      { sectionType: 'gallery', variantKey: 'classic', order: 3 },
      { sectionType: 'schedule', variantKey: 'classic', order: 4 },
      { sectionType: 'location', variantKey: 'classic', order: 5 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 6 },
      { sectionType: 'footer', variantKey: 'classic', order: 7 },
    ],
    createdAt: '2026-01-31',
    updatedAt: '2026-01-31',
  },
  {
    id: 'modern-luxe',
    name: 'Modern Luxe',
    description: 'Contemporary luxury experience',
    tags: ['modern', 'luxe'],
    sections: [
      { sectionType: 'hero', variantKey: 'modern', order: 0 },
      { sectionType: 'story', variantKey: 'elegant', order: 1 },
      { sectionType: 'gallery', variantKey: 'elegant', order: 2 },
      { sectionType: 'timeline', variantKey: 'modern', order: 3 },
      { sectionType: 'schedule', variantKey: 'modern', order: 4 },
      { sectionType: 'location', variantKey: 'modern', order: 5 },
      { sectionType: 'rsvp', variantKey: 'modern', order: 6 },
      { sectionType: 'footer', variantKey: 'elegant', order: 7 },
    ],
    createdAt: '2026-02-01',
    updatedAt: '2026-02-01',
  },
  {
    id: 'elegant-simplicity',
    name: 'Elegant Simplicity',
    description: 'Sophisticated and uncluttered',
    tags: ['elegant', 'minimal'],
    sections: [
      { sectionType: 'hero', variantKey: 'elegant', order: 0 },
      { sectionType: 'story', variantKey: 'elegant', order: 1 },
      { sectionType: 'gallery', variantKey: 'elegant', order: 2 },
      { sectionType: 'location', variantKey: 'minimal', order: 3 },
      { sectionType: 'rsvp', variantKey: 'minimal', order: 4 },
      { sectionType: 'footer', variantKey: 'elegant', order: 5 },
    ],
    createdAt: '2026-02-02',
    updatedAt: '2026-02-02',
  },
  {
    id: 'rustic-charm',
    name: 'Rustic Charm',
    description: 'Warm and inviting countryside feel',
    tags: ['rustic', 'classic'],
    sections: [
      { sectionType: 'hero', variantKey: 'classic', order: 0 },
      { sectionType: 'story', variantKey: 'classic', order: 1 },
      { sectionType: 'timeline', variantKey: 'classic', order: 2 },
      { sectionType: 'gallery', variantKey: 'carousel', order: 3 },
      { sectionType: 'location', variantKey: 'classic', order: 4 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 5 },
      { sectionType: 'footer', variantKey: 'classic', order: 6 },
    ],
    createdAt: '2026-02-03',
    updatedAt: '2026-02-03',
  },
  {
    id: 'urban-modern',
    name: 'Urban Modern',
    description: 'City-inspired contemporary design',
    tags: ['modern', 'bold'],
    sections: [
      { sectionType: 'hero', variantKey: 'modern', order: 0 },
      { sectionType: 'story', variantKey: 'modern', order: 1 },
      { sectionType: 'gallery', variantKey: 'masonry', order: 2 },
      { sectionType: 'schedule', variantKey: 'modern', order: 3 },
      { sectionType: 'location', variantKey: 'modern', order: 4 },
      { sectionType: 'rsvp', variantKey: 'modern', order: 5 },
      { sectionType: 'footer', variantKey: 'classic', order: 6 },
    ],
    createdAt: '2026-02-04',
    updatedAt: '2026-02-04',
  },
  {
    id: 'garden-party',
    name: 'Garden Party',
    description: 'Fresh and outdoor-inspired',
    tags: ['whimsical', 'romantic'],
    sections: [
      { sectionType: 'hero', variantKey: 'romantic', order: 0 },
      { sectionType: 'story', variantKey: 'classic', order: 1 },
      { sectionType: 'gallery', variantKey: 'carousel', order: 2 },
      { sectionType: 'schedule', variantKey: 'cards', order: 3 },
      { sectionType: 'location', variantKey: 'classic', order: 4 },
      { sectionType: 'rsvp', variantKey: 'classic', order: 5 },
      { sectionType: 'footer', variantKey: 'elegant', order: 6 },
    ],
    createdAt: '2026-02-05',
    updatedAt: '2026-02-05',
  },
];

export function getTemplateById(id: string): Template | undefined {
  return TEMPLATES.find(t => t.id === id);
}

export function getTemplatesByTag(tag: string): Template[] {
  return TEMPLATES.filter(t => t.tags?.includes(tag as any));
}

export function getAllTemplates(): Template[] {
  return TEMPLATES;
}
